class: src.models.mnist_model.LitModelMNIST
args:
    optimizer_config: ${optimizer}
    architecture: SimpleDenseNet
    input_size: 784
    lin1_size: 256
    dropout1: 0.30
    lin2_size: 256
    dropout2: 0.25
    lin3_size: 128
    dropout3: 0.20
    output_size: 10
