defaults:
    - default_callbacks.yaml
    - wandb_callbacks.yaml


save_confusion_matrix_to_wandb:
    class: src.callbacks.wandb_callbacks.SaveConfusionMatrixToWandb
    args:
        class_names: ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']


save_f1_precision_recall_heatmap_to_wandb:
    class: src.callbacks.wandb_callbacks.SaveMetricsHeatmapToWandb
    args:
        class_names: ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']
