defaults:
  - model_checkpoint.yaml
  - early_stopping.yaml
  - model_summary.yaml
  - rich_progress_bar.yaml
  - _self_

model_checkpoint:
  dirpath: ${paths.output_dir}/checkpoints
  filename: "epoch_{epoch:03d}"
  monitor: "val/loss" #"val/acc"
  mode: "min" #"max"
  save_last: True
  auto_insert_metric_name: False

early_stopping:
  monitor:  "val/loss" #"val/acc"
  patience: 100
  mode: "min" #"max"

model_summary:
  max_depth: -1
