defaults:
    - default_callbacks.yaml


upload_code_to_wandb_as_artifact:
    _target_: src.pl_callbacks.wandb_callbacks.UploadCodeToWandbAsArtifact
    code_dir: ${work_dir}


upload_ckpts_to_wandb_as_artifact:
    _target_: src.pl_callbacks.wandb_callbacks.UploadCheckpointsToWandbAsArtifact
    ckpt_dir: "checkpoints/"
    upload_best_only: True


watch_model_with_wandb:
    _target_: src.pl_callbacks.wandb_callbacks.WatchModelWithWandb
    log: "all"
    log_freq: 100


save_f1_precision_recall_heatmap_to_wandb:
    _target_: src.pl_callbacks.wandb_callbacks.LogF1PrecRecHeatmapToWandb


save_confusion_matrix_to_wandb:
    _target_: src.pl_callbacks.wandb_callbacks.LogConfusionMatrixToWandb
