# @package _global_

defaults:
  - _self_
  - datamodule: mnist.yaml # choose datamodule with test_dataloader for evaluation
  - model: mnist.yaml
  - logger: null
  - trainer: default.yaml
  - hydra: default.yaml
  - paths: default.yaml

task_name: "eval"

name: "default"

tags: ["mnist"]

ignore_warnings: False

print_config: True

# passing checkpoint path is necessary for evaluation
ckpt_path: ???
